const fs = require('fs');
const dir = require('node:path').resolve(__dirname, '..');
global.window = {}; for(const n of ['vocabulary','lessons','grammar','readings','connections']) require(dir+'/data/'+n+'.js');
const B=(es,en)=>({es,en});
const T=(es,en,columns,rows,noteEs,noteEn)=>({title:B(es,en),columns:columns.map(c=>Array.isArray(c)?B(c[0],c[1]):B(c,c)),rows,note:B(noteEs,noteEn)});
const P=['ich','du','er / sie / es','wir','ihr','sie / Sie'];
const parallel=(...forms)=>P.map((p,i)=>[p,...forms.map(f=>f[i])]);
const C=[['Caso','Case'],['Masculino','Masculine'],['Femenino','Feminine'],['Neutro','Neuter'],['Plural','Plural']];
const S={};
function U(n,es,en,steps,tables,primary,readings,extra=[]){const id='unit-'+String(n).padStart(2,'0');S[id]={overview:B(es,en),steps:steps.map(s=>B(...s)),appliedTables:tables,primaryReadingId:primary,readingSequence:readings||[primary],prerequisites:n===1?[]:['unit-'+String(n-1).padStart(2,'0')],readingGrammarIds:extra};}
U(1,'Construye una proposición y cambia el primer constituyente sin perder V2. Memoriza sein y las terminaciones; aus Chile / in Santiago funcionan aquí como expresiones completas.','Build a proposition and change the first constituent without losing V2. Memorise sein and the endings; aus Chile / in Santiago are learned here as complete expressions.',[
['Reconstruye sujeto → verbo conjugado → complemento. La posición cuenta constituyentes, no palabras.','Reconstruct subject → finite verb → complement. Positions count constituents, not words.'],
['Contrasta come / comes con komme / kommst / kommt; el alemán distingue más personas que el inglés.','Contrast come / comes with komme / kommst / kommt; German marks more persons than English.'],
['Recupera el paradigma sin verlo; después lee y transforma Ich komme… → Heute komme ich…','Recall the paradigm without looking; then read and transform Ich komme… → Heute komme ich…']],[
T('Präsens aplicado · ser/estar, venir, llamarse y residir','Applied Präsens · be, come, be called and live',[['Persona','Person'],'sein','kommen','heißen','wohnen','sprechen'],parallel(['bin','bist','ist','sind','seid','sind'],['komme','kommst','kommt','kommen','kommt','kommen'],['heiße','heißt','heißt','heißen','heißt','heißen'],['wohne','wohnst','wohnt','wohnen','wohnt','wohnen'],['spreche','sprichst','spricht','sprechen','sprecht','sprechen']),'er/sie/es comparten forma; sie/Sie = ellos/usted(es). sprechen cambia e→i en du/er. Nominativ: ich es sujeto.','er/sie/es share a form; sie/Sie = they/formal you. sprechen changes e→i in du/er. Nominativ: ich is the subject.'),
T('V2 aplicado · una posición puede tener varias palabras','Applied V2 · a position may contain several words',[['Posición 1','Position 1'],['Verbo (2)','Verb (2)'],['Resto','Remainder'],['Significado','Meaning']],[[ 'Ich','komme','aus Chile.',B('Soy de Chile.','I am from Chile.')],['Heute','wohne','ich in Santiago.',B('Hoy vivo en Santiago.','Today I live in Santiago.')],['Der Lehrer','heißt','Paul.',B('El profesor se llama Paul.','The teacher is called Paul.')],['Wir','sind','hier.',B('Estamos aquí.','We are here.')]],'El inglés mantiene normalmente sujeto–verbo; V2 permite adelantar Heute. Sustantivos con mayúscula; Lehrer = profesor.','English normally keeps subject–verb order; V2 allows Heute first. Nouns are capitalised; Lehrer = teacher.')], 'reading-unit-01', ['reading-unit-01'], ['present','personal-pronouns','word-order']);
U(2,'Distingue Nominativ (sujeto) y Akkusativ (objeto de sehen/haben). Aprende artículo + nombre + plural como una entrada.','Distinguish Nominativ (subject) and Akkusativ (object of sehen/haben). Learn article + noun + plural as one entry.',[
['Marca quién ve y qué ve antes de elegir el artículo.','Mark who sees and what is seen before choosing the article.'],
['Alterna nombre y pronombre: Ich sehe den Hund → Ich sehe ihn.','Alternate noun and pronoun: Ich sehe den Hund → Ich sehe ihn.'],
['Consulta las cuatro filas como mapa; hoy recupera solo Nom/Akk. Dativo y genitivo se trabajan en U05/U08.','Use the four rows as a map; recall only Nom/Akk today. Dative and genitive are practised in U05/U08.']],[
T('Artikel + Nomen · definido, cuatro casos aplicados','Artikel + Nomen · definite, four applied cases',C,[['Nom','der Hund','die Frau','das Buch','die Hunde'],['Akk','den Hund','die Frau','das Buch','die Hunde'],['Dat · U05','dem Hund','der Frau','dem Buch','den Hunden'],['Gen · U08','des Hundes','der Frau','des Buches','der Hunde']],'Hund perro; Frau mujer; Buch libro. Gen singular masculino/neutro añade -(e)s; Dat plural añade -n. Las dos últimas filas son referencia anticipada.','Hund dog; Frau woman; Buch book. Masculine/neuter Gen singular adds -(e)s; Dat plural adds -n. The last two rows are advance reference.'),
T('ein aplicado · indefinido y ausencia de plural','Applied ein · indefinite and no plural form',C,[['Nom','ein Hund','eine Frau','ein Buch','Hunde (∅)'],['Akk','einen Hund','eine Frau','ein Buch','Hunde (∅)'],['Dat · U05','einem Hund','einer Frau','einem Buch','Hunden (∅)'],['Gen · U08','eines Hundes','einer Frau','eines Buches','Hunde (∅)']],'ein no tiene plural. der→den / ein→einen únicamente en masculino Akk singular.','ein has no plural. der→den / ein→einen only in masculine Akk singular.'),
T('Pronombres y verbos · ver/tener','Pronouns and verbs · see/have',[['Sujeto','Subject'],['Objeto Akk','Akk object'],'sehen','haben'],[['ich','mich','sehe','habe'],['du','dich','siehst','hast'],['er','ihn','sieht','hat'],['sie','sie','sieht','hat'],['es','es','sieht','hat'],['wir','uns','sehen','haben'],['ihr','euch','seht','habt'],['sie / Sie','sie / Sie','sehen','haben']],'Ich sehe den Hund = veo al perro; Ich sehe ihn = lo veo. El género del pronombre sigue al nombre alemán.','Ich sehe den Hund = I see the dog; Ich sehe ihn = I see him/it. The pronoun follows the German noun’s gender.')], 'reading-unit-02',null,['articles','cases','accusative','personal-pronouns']);
U(3,'Pregunta por una posición vacía; después niega el elemento preciso. kein modifica el nombre, nicht modifica la proposición o un constituyente.','Ask for a missing constituent; then negate the precise element. kein modifies a noun, nicht a proposition or constituent.',[
['Transforma afirmación → pregunta sí/no (verbo primero) → W-Frage (interrogativo primero).','Transform statement → yes/no question (verb first) → W-Frage (question word first).'],
['Elige kein con nombre indefinido; elige nicht para adjetivo, verbo o contraste.','Choose kein with an indefinite noun; choose nicht for an adjective, verb or contrast.'],
['La traducción no determina por sí sola el caso: wer sujeto, wen objeto, wem destinatario (U05).','Translation alone does not determine case: wer subject, wen object, wem recipient (U05).']],[
T('Preguntas aplicadas · misma información, tres estructuras','Applied questions · same information, three structures',[['Función','Function'],['Estructura','Structure'],['Ejemplo','Example'],['Significado','Meaning']],[[B('Afirmación','Statement'),B('sujeto + verbo + resto','subject + verb + remainder'),'Du liest ein Buch.',B('Lees un libro.','You read a book.')],[B('Sí/no','Yes/no'),B('verbo + sujeto + resto','verb + subject + remainder'),'Liest du ein Buch?',B('¿Lees un libro?','Do you read a book?')],[B('Objeto','Object'),B('was + verbo + sujeto','was + verb + subject'),'Was liest du?',B('¿Qué lees?','What do you read?')],[B('Sujeto','Subject'),B('wer + verbo + resto','wer + verb + remainder'),'Wer liest das Buch?',B('¿Quién lee el libro?','Who reads the book?')],[B('Lugar / origen','Place / origin'),B('wo / woher + verbo','wo / woher + verb'),'Wo wohnst du? / Woher kommst du?',B('¿Dónde vives? / ¿De dónde eres?','Where do you live? / Where are you from?')]],'was qué; wer quién; wen a quién (Akk); wo dónde; woher de dónde; wann cuándo; wie cómo; warum por qué.','was what; wer who; wen whom (Akk); wo where; woher where from; wann when; wie how; warum why.'),
T('kein / nicht aplicado · el alcance decide','Applied kein / nicht · scope determines the choice',[['Base','Base'],['Negación','Negation'],['Lectura','Meaning']], [['Ich habe einen Hund.','Ich habe keinen Hund.',B('No tengo perro.','I do not have a dog.')],['Ich habe ein Buch.','Ich habe kein Buch.',B('No tengo libro.','I do not have a book.')],['Ich habe Bücher.','Ich habe keine Bücher.',B('No tengo libros.','I do not have books.')],['Der Text ist einfach.','Der Text ist nicht einfach.',B('El texto no es simple.','The text is not simple.')],['Ich lese das Buch.','Ich lese das Buch nicht.',B('No leo ese libro.','I am not reading that book.')],['Ich wohne in Berlin.','Ich wohne nicht in Berlin.',B('No vivo en Berlín.','I do not live in Berlin.')]],'kein se declina como ein y sí tiene plural. nicht precede al adjetivo o al complemento negado; la negación global depende de la estructura.','kein declines like ein and does have plural forms. nicht precedes a negated adjective or complement; sentence negation depends on structure.')], 'reading-unit-03',null,['questions','negation','word-order']);
U(4,'Construye el marco verbal: modal conjugado + infinitivo, o verbo conjugado + prefijo separable. Distingue capacidad, obligación, permiso y deseo.','Build the verbal bracket: finite modal + infinitive, or finite verb + separable prefix. Distinguish ability, obligation, permission and desire.',[
['Recupera cada modal con significado y las seis personas; ich/er suelen coincidir.','Recall each modal with its meaning and all six persons; ich/er usually coincide.'],
['Mueve el sujeto sin abrir el infinitivo o perder el prefijo final.','Move the subject without splitting the infinitive or losing the final prefix.'],
['No tener que ≠ no tener permiso: nicht müssen / nicht dürfen.','Not having to ≠ not being allowed to: nicht müssen / nicht dürfen.']],[
T('Modalverben · paradigma completo del presente','Modalverben · complete present paradigm',[['Persona','Person'],'können','müssen','wollen','dürfen','sollen','mögen','möchten'],parallel(['kann','kannst','kann','können','könnt','können'],['muss','musst','muss','müssen','müsst','müssen'],['will','willst','will','wollen','wollt','wollen'],['darf','darfst','darf','dürfen','dürft','dürfen'],['soll','sollst','soll','sollen','sollt','sollen'],['mag','magst','mag','mögen','mögt','mögen'],['möchte','möchtest','möchte','möchten','möchtet','möchten']),'können poder/saber; müssen tener que; wollen querer; dürfen tener permiso; sollen deber por encargo; mögen gustar; möchten quisiera/querer cortés (Konjunktiv II de mögen, aprendido aquí como patrón).','können can/be able; müssen must/have to; wollen want; dürfen may/be allowed; sollen be supposed to; mögen like; möchten would like (Konjunktiv II of mögen, learned here as a pattern).'),
T('Satzklammer · marcos aplicados','Satzklammer · applied verbal brackets',[['Posición 1','Position 1'],['Conjugado','Finite verb'],['Centro','Middle'],['Final','Final']], [['Ich','kann','Deutsch','lernen.'],['Heute','muss','ich früh','aufstehen.'],['Ich','stehe','um sieben Uhr','auf.'],['Er','fängt','um neun Uhr','an.'],['Du','darfst','hier nicht','arbeiten.'],['Du','musst','heute nicht','arbeiten.']],'aufstehen levantarse; anfangen empezar; früh temprano; um sieben Uhr a las siete. Los infinitivos separables permanecen unidos detrás del modal.','aufstehen get up; anfangen begin; früh early; um sieben Uhr at seven. Separable infinitives remain joined after a modal.')], 'reading-unit-04',null,['modal-verbs','word-order','numbers']);
U(5,'El caso está regido por el verbo o la preposición. En espacio, contrasta ubicación con destino/cambio de relación, no inmovilidad con movimiento.','Case is governed by the verb or preposition. In space, contrast location with destination/change of relation, not stillness with movement.',[
['Reconstruye sujeto, destinatario Dat y objeto Akk: Ich gebe dem Kind das Buch.','Reconstruct subject, Dat recipient and Akk object: Ich gebe dem Kind das Buch.'],
['Aprende helfen + Dat y las preposiciones de dativo como régimen léxico.','Learn helfen + Dat and dative prepositions as lexical government.'],
['Compara sobre la mesa / hacia la mesa y movimiento dentro de un lugar.','Compare on the table / onto the table, and movement within a place.']],[
T('Dativ aplicado · pronombres y tres géneros','Applied Dativ · pronouns and three genders',[['Nom','Nom'],['Dat','Dat'],['Ejemplo','Example']], [['ich','mir','Der Lehrer hilft mir.'],['du','dir','Ich helfe dir.'],['er','ihm','Ich helfe dem Mann / ihm.'],['sie','ihr','Ich helfe der Frau / ihr.'],['es','ihm','Ich helfe dem Kind / ihm.'],['wir','uns','Er hilft uns.'],['ihr','euch','Er hilft euch.'],['sie / Sie','ihnen / Ihnen','Ich helfe den Kindern / ihnen / Ihnen.']],'helfen ayudar exige Dat. geben dar: ich gebe, du gibst, er gibt, wir geben, ihr gebt, sie geben. Den Kindern: plural añade -n.','helfen help requires Dat. geben give: ich gebe, du gibst, er gibt, wir geben, ihr gebt, sie geben. Den Kindern: plural adds -n.'),
T('Wechselpräpositionen · las nueve aplicadas','Wechselpräpositionen · all nine applied',[['Preposición','Preposition'],['Ubicación · Dat','Location · Dat'],['Destino · Akk','Destination · Akk']], [['an','Das Bild hängt an der Wand.','Ich hänge das Bild an die Wand.'],['auf','Das Buch liegt auf dem Tisch.','Ich lege das Buch auf den Tisch.'],['hinter','Der Stuhl steht hinter dem Tisch.','Ich stelle den Stuhl hinter den Tisch.'],['in','Ich bin im Zimmer.','Ich gehe ins Zimmer.'],['neben','Der Stuhl steht neben dem Bett.','Ich stelle den Stuhl neben das Bett.'],['über','Die Lampe hängt über dem Tisch.','Ich hänge die Lampe über den Tisch.'],['unter','Das Buch liegt unter dem Tisch.','Ich lege das Buch unter den Tisch.'],['vor','Der Stuhl steht vor dem Fenster.','Ich stelle den Stuhl vor das Fenster.'],['zwischen','Der Stuhl steht zwischen dem Tisch und dem Bett.','Ich stelle den Stuhl zwischen den Tisch und das Bett.']],'Wand pared; Bild cuadro; Lampe lámpara; Bett cama; Fenster ventana. liegen/stehen ubicación; legen/stellen colocar. Ich laufe im Park usa Dat aunque hay movimiento.','Wand wall; Bild picture; Lampe lamp; Bett bed; Fenster window. liegen/stehen location; legen/stellen placement. Ich laufe im Park uses Dat despite movement.')], 'reading-unit-05',null,['dative','prepositions','two-way-prepositions']);
U(6,'Expresa anterioridad conversacional con Perfekt y reconoce Präteritum. El auxiliar se elige por verbo y uso, no por traducción.','Express conversational past with Perfekt and recognise Präteritum. Choose the auxiliary by verb and usage, not translation.',[
['Separa auxiliar conjugado y participio final; reconstruye el infinitivo.','Separate finite auxiliary and final participle; reconstruct the infinitive.'],
['Memoriza las formas principales de los verbos frecuentes, incluidas las separables.','Memorise principal parts of frequent verbs, including separable verbs.'],
['Contrasta presente → Präteritum → Perfekt; no confundas tiempo con modo.','Contrast present → Präteritum → Perfekt; do not confuse tense with mood.']],[
T('Formas principales aplicadas · pasado y auxiliar','Applied principal parts · past and auxiliary',[['Infinitivo','Infinitive'],['Significado','Meaning'],['Präteritum ich/er','Präteritum ich/er'],['Perfekt ich','Perfekt ich']], [['lernen',B('aprender','learn'),'lernte','habe gelernt'],['arbeiten',B('trabajar','work'),'arbeitete','habe gearbeitet'],['lesen',B('leer','read'),'las','habe gelesen'],['sehen',B('ver','see'),'sah','habe gesehen'],['schreiben',B('escribir','write'),'schrieb','habe geschrieben'],['verstehen',B('entender','understand'),'verstand','habe verstanden'],['denken',B('pensar','think'),'dachte','habe gedacht'],['treffen',B('encontrarse con','meet'),'traf','habe getroffen'],['besuchen',B('visitar','visit'),'besuchte','habe besucht'],['gehen',B('ir','go'),'ging','bin gegangen'],['fahren',B('viajar (intransitivo)','travel (intransitive)'),'fuhr','bin gefahren'],['kommen',B('venir','come'),'kam','bin gekommen'],['ankommen',B('llegar','arrive'),'kam an','bin angekommen'],['aufstehen',B('levantarse','get up'),'stand auf','bin aufgestanden'],['bleiben',B('quedarse','stay'),'blieb','bin geblieben'],['werden',B('volverse','become'),'wurde','bin geworden'],['sein',B('ser/estar','be'),'war','bin gewesen']],'fahren con objeto puede usar haben: Ich habe das Auto gefahren. be-/ver-/ent- y -ieren no llevan ge-. Para sein se practican cambios de lugar/estado intransitivos y los verbos señalados.','Transitive fahren can use haben: Ich habe das Auto gefahren. be-/ver-/ent- and -ieren take no ge-. Practise sein with the intransitive changes of location/state and listed verbs.'),
T('Präteritum aplicado · paradigma de pasado','Applied Präteritum · past paradigm',[['Persona','Person'],'sein','haben','lernen','lesen'],parallel(['war','warst','war','waren','wart','waren'],['hatte','hattest','hatte','hatten','hattet','hatten'],['lernte','lerntest','lernte','lernten','lerntet','lernten'],['las','lasest','las','lasen','last','lasen']),'Ich las = leí/leía. El alemán no reparte Präteritum en perfecto/imperfecto españoles; el contexto decide. du lasest (también du last); ihr last.','Ich las = I read/was reading. German Präteritum does not reproduce the Spanish preterite/imperfect distinction; context decides. du lasest (also du last); ihr last.')], 'reading-unit-06',null,['perfect','past','irregular-verbs']);
U(7,'Empaqueta causa, contenido, condición y pregunta indirecta en subordinadas con verbo final. Conserva el marco modal o perfecto.','Package reason, content, condition and indirect question in subordinate clauses with a final finite verb. Preserve modal or perfect brackets.',[
['Clasifica el nexo por significado; el orden depende de su clase, no de la traducción.','Classify the connector by meaning; order follows its class, not its translation.'],
['Si la subordinada va delante, toda ella ocupa posición 1 de la principal.','When a subordinate clause comes first, the whole clause occupies position 1 of the main clause.'],
['Recupera la misma oración en orden principal→subordinada y subordinada→principal.','Recall the same sentence in main→subordinate and subordinate→main order.']],[
T('Subordinantes aplicados · significado y verbo final','Applied subordinators · meaning and final verb',[['Nexo','Connector'],['Significado','Meaning'],['Ejemplo','Example']], [['weil',B('porque','because'),'Ich lese, weil der Text interessant ist.'],['dass',B('que: contenido','that: content'),'Ich weiß, dass er Deutsch lernt.'],['wenn',B('si/cuando: condición o repetición','if/when: condition or recurrence'),'Wenn ich Zeit habe, lese ich.'],['ob',B('si: pregunta indirecta','whether: indirect question'),'Ich frage, ob er hier wohnt.'],['obwohl',B('aunque','although'),'Ich lese, obwohl ich müde bin.'],['als',B('cuando: evento único pasado','when: single past event'),'Als ich in Berlin war, habe ich Deutsch gelernt.']],'Coma obligatoria entre principal y subordinada. ob no introduce una condición; wenn no introduce una pregunta indirecta.','A comma separates main and subordinate clauses. ob does not introduce a condition; wenn does not introduce an indirect question.'),
T('Verbo final aplicado · simple, modal y perfecto','Applied final verb · simple, modal and perfect',[['Principal','Main clause'],['Subordinada','Subordinate clause'],['Con subordinada inicial','With initial subordinate clause']], [['Ich lese den Text.','weil ich den Text lese','Weil ich den Text lese, lerne ich Deutsch.'],['Ich kann den Text lesen.','weil ich den Text lesen kann','Weil ich den Text lesen kann, bin ich froh.'],['Ich habe den Text gelesen.','weil ich den Text gelesen habe','Weil ich den Text gelesen habe, kenne ich die Antwort.'],['Ich stehe früh auf.','weil ich früh aufstehe','Weil ich früh aufstehe, habe ich Zeit.']],'La forma separable se reúne: aufstehe. froh contento; Antwort respuesta. No inviertas la subordinada como si fuera una pregunta inglesa.','The separable form rejoins: aufstehe. froh glad; Antwort answer. Do not invert a subordinate clause like an English question.')], 'reading-unit-07',null,['subordinate','word-order','connectors']);
U(8,'Conecta poseedor y objeto sin proyectar el género del español. Reconoce genitivo, contracciones y referencia temporal.','Connect possessor and object without projecting Spanish gender. Recognise genitive, contractions and time reference.',[
['La raíz posesiva identifica al poseedor; la terminación identifica género/número/caso de lo poseído.','The possessive stem identifies the possessor; the ending identifies gender/number/case of the possessed noun.'],
['Declina der Hund y das Buch en todos los casos y distingue el genitivo del objeto acusativo.','Decline der Hund and das Buch in all cases and distinguish genitive from accusative object.'],
['Lee rutina y relato completos; traduce im/am/zur mediante sus componentes.','Read a complete routine and narrative; translate im/am/zur through their components.']],[
T('Possessivartikel · poseedor y raíz','Possessivartikel · possessor and stem',[['Poseedor','Possessor'],['Raíz','Stem'],['Aplicación','Application']], [['ich','mein','mein Buch'],['du','dein','dein Buch'],['er / es','sein','sein Buch'],['sie (singular)','ihr','ihr Buch'],['wir','unser','unser Buch'],['ihr','euer','euer Buch'],['sie (plural)','ihr','ihr Buch'],['Sie','Ihr','Ihr Buch']],'mein mi; dein tu; sein su de él/ello; ihr su de ella/ellos; unser nuestro; euer vuestro; Ihr su formal. La mayúscula Ihr identifica el trato formal salvo inicio de oración.','mein my; dein your; sein his/its; ihr her/their; unser our; euer your plural; Ihr formal your. Capital Ihr identifies formal address except at sentence start.'),
T('mein aplicado · cuatro casos con lo poseído','Applied mein · four cases of the possessed noun',C,[['Nom','mein Hund','meine Frau','mein Buch','meine Bücher'],['Akk','meinen Hund','meine Frau','mein Buch','meine Bücher'],['Dat','meinem Hund','meiner Frau','meinem Buch','meinen Büchern'],['Gen','meines Hundes','meiner Frau','meines Buches','meiner Bücher']],'euer pierde normalmente e al añadir terminación: eure Frau / eurem Hund. No cambia el género por ser poseído por una mujer: ihr Hund.','euer normally loses e before an ending: eure Frau / eurem Hund. A female possessor does not change noun gender: ihr Hund.'),
T('Genitiv aplicado · tipo de nombre y régimen','Applied Genitiv · noun type and government',[['Base','Base'],['Relación','Relationship'],['Significado','Meaning']], [['der Lehrer','das Buch des Lehrers',B('el libro del profesor','the teacher’s book')],['das Kind','das Buch des Kindes',B('el libro del niño','the child’s book')],['die Frau','das Buch der Frau',B('el libro de la mujer','the woman’s book')],['die Kinder','das Buch der Kinder',B('el libro de los niños','the children’s book')],['der Mensch','die Freiheit des Menschen',B('la libertad del ser humano','human freedom')],['das Wetter','wegen des Wetters',B('por el clima','because of the weather')]],'Mensch tiene declinación débil: den/dem/des Menschen. fuera de = außerhalb + Gen; apesar de = trotz + Gen en registro formal.','Mensch has weak declension: den/dem/des Menschen. outside = außerhalb + Gen; despite = trotz + Gen in formal standard usage.'),
T('Futur I aplicado · werden + infinitivo','Applied Futur I · werden + infinitive',[['Persona','Person'],['werden','werden'],['Ejemplo','Example']],parallel(['werde','wirst','wird','werden','werdet','werden']).map((r,i)=>[...r,`${P[i].replace(' / sie / es','').replace('sie / Sie','sie')} ${r[1]} morgen lesen.`]),'Morgen lese ich suele bastar: mañana leeré. Futur I también puede expresar conjetura. werden aquí es auxiliar, no volverse.','Morgen lese ich often suffices: I will read tomorrow. Futur I can also express conjecture. werden is an auxiliary here, not become.')], 'reading-unit-08',['reading-unit-08','reading-a1-2','reading-a1-3','reading-a1-4','reading-a2-1'],['possessives','genitive','future','noun-declension']);
U(9,'La marca de caso se distribuye entre determinante y adjetivo. Resuelve el caso del relativo dentro de su propia oración. Introduce aquí la comparación elemental para las lecturas.','Case marking is distributed between determiner and adjective. Resolve the relative pronoun’s case inside its own clause. Introduce basic comparison here for the readings.',[
['Calcula caso → género/número → determinante → terminación del adjetivo.','Determine case → gender/number → determiner → adjective ending.'],
['Reconstruye el antecedente en la relativa: der Mann… ich helfe dem Mann → dem ich helfe.','Restore the antecedent in the relative clause: der Mann… ich helfe dem Mann → dem ich helfe.'],
['Compara guter Text / der gute Text / ein guter Text; explica quién lleva la marca.','Compare guter Text / der gute Text / ein guter Text; explain where the case marker is carried.']],[
T('Schwach · gut con artículo definido, completo','Weak · gut with definite article, complete',C,[['Nom','der gute Mann','die gute Frau','das gute Buch','die guten Bücher'],['Akk','den guten Mann','die gute Frau','das gute Buch','die guten Bücher'],['Dat','dem guten Mann','der guten Frau','dem guten Buch','den guten Büchern'],['Gen','des guten Mannes','der guten Frau','des guten Buches','der guten Bücher']],'gut bueno; Mann hombre; Frau mujer; Buch libro. Tras der: -e en Nom singular y Akk femenino/neutro; -en en el resto.','gut good; Mann man; Frau woman; Buch book. After der: -e in Nom singular and feminine/neuter Akk; -en elsewhere.'),
T('Gemischt · gut con ein/kein, completo','Mixed · gut with ein/kein, complete',C,[['Nom','ein guter Mann','eine gute Frau','ein gutes Buch','keine guten Bücher'],['Akk','einen guten Mann','eine gute Frau','ein gutes Buch','keine guten Bücher'],['Dat','einem guten Mann','einer guten Frau','einem guten Buch','keinen guten Büchern'],['Gen','eines guten Mannes','einer guten Frau','eines guten Buches','keiner guten Bücher']],'ein no tiene plural: se usa kein para mostrarlo. mein sigue el mismo patrón. Donde ein no lleva terminación, el adjetivo aporta -er/-es.','ein has no plural: kein illustrates plural forms. mein follows this pattern. When ein has no ending, the adjective supplies -er/-es.'),
T('Stark · gut sin artículo, completo','Strong · gut without an article, complete',C,[['Nom','guter Wein','gute Musik','gutes Brot','gute Bücher'],['Akk','guten Wein','gute Musik','gutes Brot','gute Bücher'],['Dat','gutem Wein','guter Musik','gutem Brot','guten Büchern'],['Gen','guten Weines','guter Musik','guten Brotes','guter Bücher']],'Wein vino; Musik música; Brot pan. Gen masculino/neutro fuerte del adjetivo acaba en -en: guten Weines, no gutes Weines.','Wein wine; Musik music; Brot bread. Strong masculine/neuter Gen adjective ends in -en: guten Weines, not gutes Weines.'),
T('Relativpronomen aplicado · las cuatro funciones','Applied Relativpronomen · all four functions',C,[['Nom','der Mann, der liest','die Frau, die liest','das Kind, das liest','die Kinder, die lesen'],['Akk','der Mann, den ich sehe','die Frau, die ich sehe','das Kind, das ich sehe','die Kinder, die ich sehe'],['Dat','der Mann, dem ich helfe','die Frau, der ich helfe','das Kind, dem ich helfe','die Kinder, denen ich helfe'],['Gen','der Mann, dessen Buch ich lese','die Frau, deren Buch ich lese','das Kind, dessen Buch ich lese','die Kinder, deren Buch ich lese']],'Género/número = antecedente; caso = función en relativa. dessen/deren = cuyo/a(s), sin concordar con Buch. Se cierra la relativa con coma si continúa la principal.','Gender/number = antecedent; case = role in the relative clause. dessen/deren = whose, without agreeing with Buch. Close the relative clause with a comma when the main clause continues.'),
T('Comparación elemental · preparación de lecturas','Basic comparison · reading preparation',[['Base','Base'],['Comparativo','Comparative'],['Superlativo adverbial','Adverbial superlative'],['Aplicación','Application']], [['gut','besser','am besten','Ich verstehe den Text besser.'],['einfach','einfacher','am einfachsten','Dieser Text ist einfacher als der andere.'],['schwierig','schwieriger','am schwierigsten','Das Buch ist schwieriger.'],['viel','mehr','am meisten','Ich habe mehr Zeit.'],['kurz','kürzer','am kürzesten','Der Text ist kürzer.']],'Comparativo + als = más… que; so… wie = tan… como. Atributivo: ein schwierigeres Buch. U16 retoma comparación y tiempo; aquí se aprende el patrón necesario.','Comparative + als = more… than; so… wie = as… as. Attributive: ein schwierigeres Buch. U16 revisits comparison and time; learn the required pattern here.')], 'reading-a1-1',['reading-a1-1','reading-a2-2','reading-a2-3','reading-a2-4','reading-b1-4'],['adjective-endings','relative','comparative','demonstratives']);
U(10,'Distingue un proceso pasivo, un estado resultante y una oración activa. Conserva el dativo; solo el objeto acusativo se convierte en sujeto.','Distinguish a passive process, a resulting state and an active sentence. Preserve dative; only the accusative object becomes the subject.',[
['Reconstruye la activa antes de formar la pasiva.','Restore the active sentence before forming the passive.'],
['Contrasta wird geöffnet / ist geöffnet: abrirse en proceso / estar abierta.','Contrast wird geöffnet / ist geöffnet: being opened / being open.'],
['Cambia presente→pasado→perfecto; recuerda worden en Perfekt pasivo. Reescribe Ich sehe die Tassen → Die Tassen werden gesehen y observa qué actor se omite.','Change present→past→perfect; remember worden in passive Perfekt. Rewrite Ich sehe die Tassen → Die Tassen werden gesehen and notice which actor is omitted.']],[
T('Vorgangspassiv · lesen en tiempos aplicados','Vorgangspassiv · lesen in applied tenses',[['Tiempo','Tense'],['Activa','Active'],['Pasiva de proceso','Process passive']], [[B('Presente','Present'),'Die Frau liest das Buch.','Das Buch wird gelesen.'],['Präteritum','Die Frau las das Buch.','Das Buch wurde gelesen.'],['Perfekt','Die Frau hat das Buch gelesen.','Das Buch ist gelesen worden.'],['Plusquamperfekt · U16','Die Frau hatte das Buch gelesen.','Das Buch war gelesen worden.'],['Futur I','Die Frau wird das Buch lesen.','Das Buch wird gelesen werden.'],[B('Modal','Modal'),'Die Frau muss das Buch lesen.','Das Buch muss gelesen werden.']],'El objeto das Buch pasa a sujeto. Agente opcional: von der Frau. Plusquamperfekt se presenta como referencia y se practica en U16.','The object das Buch becomes the subject. Optional agent: von der Frau. Plusquamperfekt is advance reference and practised in U16.'),
T('Proceso / estado / dativo conservado','Process / state / retained dative',[['Estructura','Structure'],['Ejemplo','Example'],['Lectura','Meaning']], [['werden + Partizip II','Die Tür wird geöffnet.',B('La puerta está siendo abierta.','The door is being opened.')],['sein + Partizip II','Die Tür ist geöffnet.',B('La puerta está abierta.','The door is open.')],[B('Dat permanece','Dat is retained'),'Dem Kind wird geholfen.',B('Se ayuda al niño.','The child is being helped.')],[B('Akk→Nom; Dat permanece','Akk→Nom; Dat is retained'),'Dem Kind wird das Buch gegeben.',B('Se da el libro al niño.','The book is being given to the child.')],['Modal + Partizip + werden','weil der Text gelesen werden muss',B('porque el texto debe leerse','because the text must be read')]],'Zustandspassiv designa un estado resultante; participios también pueden funcionar como adjetivos. Dem Kind no se convierte en nominativo.','Zustandspassiv denotes a resulting state; participles may also be adjectives. Dem Kind does not become nominative.')], 'reading-a2-4',['reading-a2-4','reading-b1-4'],['passive','perfect','past']);
U(11,'Formula cortesía e hipótesis con Konjunktiv II. La forma basada en Präteritum no sitúa automáticamente el hecho en el pasado.','Express politeness and hypotheses with Konjunktiv II. A form based on Präteritum does not automatically place the event in the past.',[
['Contrasta hatte / hätte y konnte / könnte antes de traducir.','Contrast hatte / hätte and konnte / könnte before translating.'],
['Prefiere wäre, hätte y modales; usa würde + infinitivo para muchos otros verbos.','Prefer wäre, hätte and modals; use würde + infinitive for many other verbs.'],
['Reformula una escena ya leída como posibilidad: Wir könnten… / Wenn ich Zeit hätte…','Reframe a previously read scene as a possibility: Wir könnten… / Wenn ich Zeit hätte…']],[
T('Konjunktiv II · paradigma aplicado completo','Konjunktiv II · complete applied paradigm',[['Persona','Person'],'sein','haben','können','müssen','würde + lesen'],parallel(['wäre','wär(e)st','wäre','wären','wär(e)t','wären'],['hätte','hättest','hätte','hätten','hättet','hätten'],['könnte','könntest','könnte','könnten','könntet','könnten'],['müsste','müsstest','müsste','müssten','müsstet','müssten'],['würde lesen','würdest lesen','würde lesen','würden lesen','würdet lesen','würden lesen']),'wäre sería/estuviera; hätte tendría; könnte podría; müsste tendría que. wärst/wärest y wärt/wäret son variantes.','wäre would be; hätte would have; könnte could; müsste would have to. wärst/wärest and wärt/wäret are variants.'),
T('Präteritum modal / hipótesis / cortesía','Modal Präteritum / hypothesis / politeness',[['Pasado real','Actual past'],['Hipótesis','Hypothesis'],['Significado del contraste','Meaning of the contrast']], [['Ich konnte lesen.','Ich könnte lesen.',B('Pude/podía leer → podría leer.','I could/was able to read → I could read (hypothetically).')],['Ich musste arbeiten.','Ich müsste arbeiten.',B('Tuve/tenía que trabajar → tendría que trabajar.','I had to work → I would have to work.')],['Ich wollte ein Buch.','Ich möchte ein Buch.',B('Quería un libro → quisiera un libro (patrón U04).','I wanted a book → I would like a book (U04 pattern).')],['Ich hatte Zeit.','Wenn ich Zeit hätte, würde ich lesen.',B('Tenía tiempo → si tuviera tiempo, leería.','I had time → if I had time, I would read.')],['Sie konnten helfen.','Könnten Sie bitte helfen?',B('Pudo/pudieron ayudar → ¿podría(n) ayudar?','You were able to help → could you please help?')]],'konnte/musste/wollte no llevan umlaut; könnte/müsste sí. En lectura, los modales pasados se flexionan como lernte: konnte, konntest, konnte, konnten, konntet, konnten.','konnte/musste/wollte have no umlaut; könnte/müsste do. Past modals inflect like lernte: konnte, konntest, konnte, konnten, konntet, konnten.')], 'reading-a2-1',['reading-a2-1','reading-a2-2'],['konjunktiv2','modal-verbs']);
U(12,'Reconoce el sujeto implícito del infinitivo y el objeto reflexivo. La finalidad puede requerir um…zu o damit según el sujeto.','Identify the infinitive’s implicit subject and the reflexive object. Purpose may require um…zu or damit depending on the subject.',[
['Reconstruye quién hace cada acción antes de elegir um…zu/damit.','Restore who performs each action before choosing um…zu/damit.'],
['Con modal no aparece zu; con separable zu se inserta entre prefijo y raíz.','Modals take no zu; separable verbs insert zu between prefix and stem.'],
['Distingue mich de mir identificando si ya existe un objeto acusativo.','Distinguish mich from mir by checking whether an accusative object already exists.']],[
T('Infinitiv aplicado · ocho marcos','Applied Infinitiv · eight frames',[['Patrón','Pattern'],['Ejemplo','Example'],['Significado','Meaning']], [['modal + Infinitiv','Ich muss lernen.',B('Tengo que aprender.','I have to learn.')],['versuchen + zu','Ich versuche, Deutsch zu lernen.',B('Intento aprender alemán.','I try to learn German.')],['separable + zu','Ich versuche, früh aufzustehen.',B('Intento levantarme temprano.','I try to get up early.')],['um…zu','Ich lese, um Deutsch zu lernen.',B('Leo para aprender alemán.','I read to learn German.')],['damit + verbo final','Ich helfe dir, damit du lernen kannst.',B('Te ayudo para que puedas aprender.','I help you so that you can learn.')],['ohne…zu','Ich lese, ohne zu sprechen.',B('Leo sin hablar.','I read without speaking.')],['statt…zu','Ich lese, statt zu schlafen.',B('Leo en vez de dormir.','I read instead of sleeping.')],['haben / sein + zu','Der Text ist zu prüfen.',B('El texto debe/puede comprobarse (según contexto).','The text must/can be checked (context determines the reading).')]],'um/ohne/statt + zu llevan coma. um…zu suele compartir sujeto con la principal; damit permite un sujeto distinto. schlafen dormir.','um/ohne/statt + zu take a comma. um…zu normally shares the main clause’s subject; damit permits a different subject. schlafen sleep.'),
T('Reflexivpronomen aplicado · Akk y Dat completos','Applied Reflexivpronomen · complete Akk and Dat',[['Sujeto','Subject'],['Akk · erinnern','Akk · erinnern'],['Dat · Hände waschen','Dat · Hände waschen']], [['ich','Ich erinnere mich an den Text.','Ich wasche mir die Hände.'],['du','Du erinnerst dich an den Text.','Du wäschst dir die Hände.'],['er / sie / es','Er erinnert sich an den Text.','Er wäscht sich die Hände.'],['wir','Wir erinnern uns an den Text.','Wir waschen uns die Hände.'],['ihr','Ihr erinnert euch an den Text.','Ihr wascht euch die Hände.'],['sie / Sie','Sie erinnern sich an den Text.','Sie waschen sich die Hände.']],'sich erinnern an + Akk recordar; sich die Hände waschen lavarse las manos. die Hände es objeto Akk; mir es Dat. sich no señala por sí mismo un caso visible.','sich erinnern an + Akk remember; sich die Hände waschen wash one’s hands. die Hände is Akk object; mir is Dat. sich does not visibly distinguish case.')], 'reading-b1-1',['reading-b1-1','reading-b1-2','reading-b1-3'],['infinitive','reflexive','relative','konjunktiv2','passive']);
U(13,'Distingue causa, consecuencia, concesión y contraste; la clase del conector predice el orden. Mantén elementos paralelos en coordinaciones dobles.','Distinguish reason, consequence, concession and contrast; connector class predicts word order. Keep coordinated elements parallel in paired constructions.',[
['Clasifica subordinante / coordinante / adverbio antes de producir la frase.','Classify subordinator / coordinator / adverb before producing the sentence.'],
['Reconstruye premisa y conclusión; obwohl y trotzdem conservan una conclusión contra una expectativa.','Restore premise and conclusion; obwohl and trotzdem retain a conclusion against an expectation.'],
['Localiza lo comparado en zwar…aber y nicht nur…sondern auch.','Locate the compared elements in zwar…aber and nicht nur…sondern auch.']],[
T('Conectores aplicados · misma premisa, tres órdenes','Applied connectors · one premise, three orders',[['Clase','Class'],['Nexo','Connector'],['Aplicación','Application']], [[B('Subordinante: verbo final','Subordinator: verb final'),'weil','Ich bleibe hier, weil es regnet.'],[B('Coordinante: principal','Coordinator: main clause'),'denn','Ich bleibe hier, denn es regnet.'],[B('Adverbio: V2','Adverb: V2'),'deshalb','Es regnet; deshalb bleibe ich hier.'],[B('Subordinante: concesión','Subordinator: concession'),'obwohl','Obwohl es regnet, gehe ich hinaus.'],[B('Adverbio: concesión','Adverb: concession'),'trotzdem','Es regnet; trotzdem gehe ich hinaus.'],[B('Subordinante: medio','Subordinator: means'),'indem','Er prüft die These, indem er Daten vergleicht.']],'regnen llover; hinausgehen salir; prüfen comprobar. deshalb por eso; trotzdem aun así; indem mediante/al hacer. denn no ocupa posición 1.','regnen rain; hinausgehen go outside; prüfen check. deshalb therefore; trotzdem nevertheless; indem by doing. denn does not occupy position 1.'),
T('Conectores dobles · argumento aplicado','Paired connectors · applied argument',[['Nexo','Connector'],['Ejemplo','Example'],['Función','Function']], [['zwar…aber','Das Buch ist zwar kurz, aber schwierig.',B('Si bien…pero: concesión.','Admittedly…but: concession.')],['sowohl…als auch','Wir prüfen sowohl die Theorie als auch die Daten.',B('Tanto…como: inclusión.','Both…and: inclusion.')],['weder…noch','Das ist weder ein Beweis noch eine Erklärung.',B('Ni…ni: doble exclusión.','Neither…nor: double exclusion.')],['nicht nur…sondern auch','Wir prüfen nicht nur die Daten, sondern auch die Annahmen.',B('No solo…sino también: ampliación.','Not only…but also: addition.')],['je…desto · U18','Je häufiger wir üben, desto leichter lernen wir.',B('Cuanto más…más: covariación.','The more…the more: covariation.')]],'Mantén paralelos los grupos nominales o cláusulas. Annahme supuesto; Beweis prueba; üben practicar. je…desto se practica a fondo en U18.','Keep noun phrases or clauses parallel. Annahme assumption; Beweis proof; üben practise. je…desto is fully practised in U18.')], 'reading-b2-1',['reading-b2-1','reading-b1-3'],['connectors','subordinate','passive','konjunktiv2']);
U(14,'Descomprime grupos nominales en acciones: participio + complementos delante del nombre, nominalización y genitivo. Distingue interpretación de sintaxis.','Expand noun phrases into actions: participle + complements before the noun, nominalisation and genitive. Distinguish interpretation from syntax.',[
['Encuentra el núcleo del grupo nominal; después determina qué elemento lo modifica.','Find the noun phrase’s head; then determine what modifies it.'],
['Transforma atributo participial → relativa → oración activa cuando sea posible.','Transform participial modifier → relative clause → active sentence when possible.'],
['El genitivo no decide siempre quién actúa: usa contexto para agente/objeto.','Genitive does not always identify the actor: use context for agent/object.']],[
T('Nominalización y participio · expansión aplicada','Nominalisation and participles · applied expansion',[['Grupo compacto','Compact phrase'],['Expansión','Expansion'],['Significado','Meaning']], [['das Lernen','Jemand lernt.',B('aprender / el aprendizaje','learning')],['die Prüfung der These','Jemand prüft die These.',B('la comprobación de la tesis','checking the thesis')],['der denkende Mensch','der Mensch, der denkt',B('el ser humano que piensa','the human who thinks')],['die von der Forscherin geprüfte These','die These, die die Forscherin geprüft hat',B('la tesis comprobada por la investigadora','the thesis checked by the researcher')],['das sich durch seine Entwicklung vollendende Wesen','das Wesen, das sich durch seine Entwicklung vollendet',B('la esencia que se completa mediante su desarrollo','the essence completing itself through its development')],['der zu verarbeitende Reiz','der Reiz, der verarbeitet werden muss/kann',B('el estímulo que debe/puede procesarse','the stimulus that must/can be processed')]],'Partizip I -d: denken→denkend; Partizip II: prüfen→geprüft. Atributivos se declinan como adjetivos. La reformulación sintáctica de Hegel no resuelve su interpretación.','Partizip I -d: denken→denkend; Partizip II: prüfen→geprüft. Attributive participles decline as adjectives. Syntactic reformulation of Hegel does not settle interpretation.'),
T('n-Deklination aplicada · Mensch / Name / Lehrer','Applied n-Deklination · Mensch / Name / Lehrer',[['Caso','Case'],'der Mensch','der Name','der Lehrer'],[['Nom','der Mensch','der Name','der Lehrer'],['Akk','den Menschen','den Namen','den Lehrer'],['Dat','dem Menschen','dem Namen','dem Lehrer'],['Gen','des Menschen','des Namens','des Lehrers']],'Mensch ser humano: débil -(e)n fuera del Nom; Name nombre: mixto Gen -ns; Lehrer profesor: fuerte Gen -s. Aprende la clase con el sustantivo.','Mensch human: weak -(e)n outside Nom; Name name: mixed Gen -ns; Lehrer teacher: strong Gen -s. Learn the class with the noun.')], 'reading-c1-1',['reading-c1-1','reading-c1-2','reading-b2-2','reading-b2-3'],['participles','adjective-endings','noun-declension','genitive','infinitive']);
U(15,'Atribuye una afirmación sin confundirte con el tiempo inglés del discurso indirecto. Konjunktiv I distingue fuente y voz del narrador.','Attribute a statement without importing English reported-speech tense shifts. Konjunktiv I distinguishes source and narrator’s voice.',[
['Identifica quién sostiene cada proposición antes de traducir el modo.','Identify who asserts each proposition before translating the mood.'],
['Compara indicativo / Konjunktiv I / sustitución por II cuando las formas coinciden.','Compare indicative / Konjunktiv I / replacement by II when forms coincide.'],
['Construye presente referido, anterioridad y pasiva manteniendo la atribución.','Build reported present, anteriority and passive while preserving attribution.']],[
T('Konjunktiv I aplicado · cuatro paradigmas completos','Applied Konjunktiv I · four complete paradigms',[['Persona','Person'],'sein','haben','kommen','können'],parallel(['sei','seiest','sei','seien','seiet','seien'],['habe','habest','habe','haben','habet','haben'],['komme','kommest','komme','kommen','kommet','kommen'],['könne','könnest','könne','können','könnet','können']),'Muchas formas coinciden con indicativo: wir haben, sie kommen. Sustitución posible por hätten/kämen o würde-forma según verbo y registro; la función puede seguir siendo discurso referido.','Many forms coincide with indicative: wir haben, sie kommen. Possible replacement by hätten/kämen or a würde-form, depending on verb and register; the function may remain reported speech.'),
T('Atribución aplicada · tiempo y voz','Applied attribution · tense and voice',[['Directo','Direct'],['Referido','Reported'],['Relación','Relationship']], [['„Ich bin müde.“','Er sagt, er sei müde.',B('Simultaneidad / estado.','Simultaneity / state.')],['„Ich habe gearbeitet.“','Er sagt, er habe gearbeitet.',B('Anterioridad con haben.','Anteriority with haben.')],['„Ich bin gekommen.“','Er sagt, er sei gekommen.',B('Anterioridad con sein.','Anteriority with sein.')],['„Die These wird geprüft.“','Der Bericht sagt, die These werde geprüft.',B('Proceso presente atribuido.','Attributed present process.')],['„Die These ist geprüft worden.“','Der Bericht sagt, die These sei geprüft worden.',B('Proceso anterior atribuido.','Attributed prior process.')],['„Regeln sind unwichtig.“','Er behauptet, Regeln seien unwichtig.',B('Afirmación atribuida; no declaración del narrador.','Attributed claim; not the narrator’s assertion.')]],'Konjunktiv I no garantiza verdad/falsedad. Er sagt (presente) puede introducir anterioridad mediante Perfekt referido; no hay retroceso temporal mecánico.','Konjunktiv I does not guarantee truth/falsity. Er sagt (present) may introduce anteriority with reported Perfekt; there is no mechanical tense backshift.')], 'reading-b2-4',['reading-b2-4','reading-b2-3'],['konjunktiv1','konjunktiv2','passive']);
U(16,'Ordena momentos antes de elegir tiempo. Plusquamperfekt necesita un punto pasado de referencia; comparación expresa relación, no mera etiqueta.','Order moments before choosing tense. Plusquamperfekt needs a past reference point; comparison expresses a relation, not just a label.',[
['Dibuja anterior→referencia pasada→ahora para distinguir Perfekt y Plusquamperfekt.','Draw earlier→past reference→now to distinguish Perfekt and Plusquamperfekt.'],
['Compara so…wie, -er…als y am…sten; la forma atributiva vuelve a declinarse.','Compare so…wie, -er…als and am…sten; attributive forms decline again.'],
['Interpreta Futur II por el contexto: futuro completado o conjetura sobre pasado.','Interpret Futur II by context: future completion or conjecture about the past.']],[
T('Plusquamperfekt aplicado · auxiliares completos','Applied Plusquamperfekt · complete auxiliaries',[['Persona','Person'],['lesen · haben','lesen · haben'],['gehen · sein','gehen · sein']],parallel(['hatte gelesen','hattest gelesen','hatte gelesen','hatten gelesen','hattet gelesen','hatten gelesen'],['war gegangen','warst gegangen','war gegangen','waren gegangen','wart gegangen','waren gegangen']),'Nachdem sie das Buch gelesen hatte, schrieb sie einen Text = después de haber leído el libro, escribió un texto. El pasado de referencia es schrieb.','Nachdem sie das Buch gelesen hatte, schrieb sie einen Text = after she had read the book, she wrote a text. The past reference point is schrieb.'),
T('Comparación y Futur II · interpretación aplicada','Comparison and Futur II · applied interpretation',[['Patrón','Pattern'],['Ejemplo','Example'],['Significado','Meaning']], [['so…wie','Dieser Text ist so schwierig wie der andere.',B('tan difícil como','as difficult as')],['-er…als','Dieser Text ist schwieriger als der andere.',B('más difícil que','more difficult than')],['am…sten','Dieser Text ist am schwierigsten.',B('el más difícil (predicativo)','the most difficult (predicative)')],[B('atributivo','attributive'),'Ich lese den schwierigeren Text.',B('leo el texto más difícil de los comparados','I read the more difficult text')],['Futur II + límite futuro','Bis morgen werde ich den Text gelesen haben.',B('Para mañana habré leído el texto.','By tomorrow I will have read the text.')],['Futur II + conjetura','Er wird den Text wohl gelesen haben.',B('Probablemente haya leído el texto.','He has probably read the text.')]],'Futur II: werde/wirst/wird/werden/werdet/werden + Partizip II + haben/sein. Comparativo no significa causalidad.','Futur II: werde/wirst/wird/werden/werdet/werden + Partizip II + haben/sein. Comparison does not imply causation.')], 'reading-b1-2',['reading-b1-2','reading-b2-1'],['past','comparative','future','subordinate']);
U(17,'Define condiciones sin invertir implicaciones. Distingue alcance de cuantificador y negación, y separa definición de afirmación empírica.','Define conditions without reversing implications. Distinguish quantifier and negation scope, and separate definitions from empirical claims.',[
['Traduce el argumento a P/Q antes de decidir necesaria o suficiente.','Translate the argument into P/Q before deciding necessary or sufficient.'],
['Identifica qué niega nicht y qué cuantifica alle/kein.','Identify what nicht negates and what alle/kein quantify.'],
['Descomprime definiciones densas y explícita sus límites.','Expand dense definitions and state their limits explicitly.']],[
T('Condiciones aplicadas · dirección lógica','Applied conditions · logical direction',[['Alemán','German'],['Estructura','Structure'],['Lectura','Meaning']], [['P gilt nur, wenn Q gilt.','P → Q',B('Q necesaria para P.','Q necessary for P.')],['Wenn Q gilt, gilt P.','Q → P',B('Q suficiente para P.','Q sufficient for P.')],['P gilt genau dann, wenn Q gilt.','P ↔ Q',B('Q necesaria y suficiente para P.','Q necessary and sufficient for P.')],['P gilt, sofern Q gilt.',B('Q → P (en lectura condicional)','Q → P (conditional reading)'),B('P se afirma bajo condición Q; revisar alcance contextual.','P is asserted under condition Q; check contextual scope.')],['Soweit bekannt, gilt P.',B('restricción epistémica','epistemic restriction'),B('P según lo conocido; no una condición bicondicional.','P as far as known; not a biconditional condition.')]],'gelten valer/aplicarse. La subordinada conserva verbo final; el símbolo representa el contenido, no el orden de las palabras.','gelten hold/apply. The subordinate clause keeps verb-final order; symbols represent content, not word order.'),
T('Definición y alcance · contrastes aplicados','Definition and scope · applied contrasts',[['Forma','Form'],['Ejemplo','Example'],['Lectura','Meaning']], [['unter + Dat','Unter diesem Begriff versteht man eine Fähigkeit.',B('Por este concepto se entiende una capacidad.','This concept is understood as an ability.')],['als + categoría','Als Beweis gilt eine gültige Ableitung.',B('Una derivación válida cuenta como prueba.','A valid derivation counts as proof.')],['nicht alle','Nicht alle Sätze sind wahr.',B('Al menos uno no es verdadero.','At least one is not true.')],['kein','Kein Satz ist wahr.',B('Ninguno es verdadero.','None is true.')],['nur','Nur dieser Satz ist wahr.',B('Este es verdadero; los demás no.','This one is true; the others are not.')],['nicht nur','Nicht nur dieser Satz ist wahr.',B('Este y por lo menos otro son verdaderos.','This one and at least one other are true.')]],'Begriff concepto; Fähigkeit capacidad; Ableitung derivación. Evita Alle Sätze sind nicht wahr si el foco puede volverla ambigua.','Begriff concept; Fähigkeit ability; Ableitung derivation. Avoid Alle Sätze sind nicht wahr when focus may make it ambiguous.')], 'reading-c1-3',['reading-c1-3','reading-c1-1'],['connectors','relative','subordinate','negation']);
U(18,'Lee covariación, proceso y evidencia sin convertir apoyo en demostración. Relaciona nominalización, participio y acción subyacente.','Read covariation, process and evidence without treating support as proof. Connect nominalisation, participles and the underlying action.',[
['Construye je…desto con comparativo en ambas partes; conserva verbo final/V2.','Build je…desto with a comparative in both parts; preserve verb-final/V2 order.'],
['Recupera verbos detrás de los nombres: Anpassung→anpassen, Verarbeitung→verarbeiten.','Recover verbs behind nouns: Anpassung→anpassen, Verarbeitung→verarbeiten.'],
['Marca qué dato apoya qué afirmación y qué inferencia queda abierta.','Mark which evidence supports which claim and which inference remains open.']],[
T('je…desto aplicado · covariación y orden','Applied je…desto · covariation and word order',[['je + comparativo, verbo final','je + comparative, verb final'],['desto + comparativo, V2','desto + comparative, V2'],['Sentido','Meaning']], [['Je häufiger man übt,','desto leichter erinnert man sich.',B('Cuanto más se practica, más fácil se recuerda.','The more often one practises, the more easily one remembers.')],['Je flexibler ein Modell ist,','desto leichter kann es Besonderheiten erfassen.',B('Cuanto más flexible el modelo, más fácil capta particularidades.','The more flexible the model, the more easily it can capture peculiarities.')],['Je mehr Daten wir prüfen,','desto genauer können wir die These beurteilen.',B('Cuantos más datos comprobamos, con mayor precisión podemos evaluar la tesis.','The more data we check, the more precisely we can assess the claim.')]],'Estos ejemplos ilustran sintaxis; no afirman leyes empíricas. desto/umso son alternativas. häufiger más a menudo; leichter más fácilmente.','These examples illustrate syntax; they do not assert empirical laws. desto/umso are alternatives. häufiger more often; leichter more easily.'),
T('Lenguaje de evidencia · inferencia aplicada','Evidence language · applied inference',[['Alemán','German'],['Significado','Meaning'],['Compromiso','Commitment']], [['Die Daten sprechen dafür, dass P gilt.',B('Los datos apoyan que P.','The data support P.'),B('Apoyo, no garantía.','Support, not guarantee.')],['Daraus folgt nicht, dass P gilt.',B('De ello no se sigue P.','P does not follow from this.'),B('Rechaza una inferencia; no implica ¬P.','Rejects an inference; does not imply ¬P.')],['A hängt mit B zusammen.',B('A está relacionado con B.','A is related to B.'),B('Relación; dirección causal sin resolver.','Relation; causal direction unresolved.')],['Der Reiz wird verarbeitet.',B('El estímulo se procesa.','The stimulus is processed.'),B('Proceso pasivo.','Passive process.')],['der zu verarbeitende Reiz',B('el estímulo que debe/puede procesarse','the stimulus that must/can be processed'),B('Atributo modal; contexto decide.','Modal modifier; context decides.')]],'sich erinnern an + Akk; zusammenhängen mit + Dat. Evidencia y prueba lógica no son equivalentes.','sich erinnern an + Akk; zusammenhängen mit + Dat. Evidence and logical proof are not equivalent.')], 'reading-c1-4',['reading-c1-4','reading-b2-2'],['comparative','participles','passive','reflexive','connectors']);
U(19,'Expresa alternativas pasadas y gradúa fuerza epistémica. Con doble infinitivo, aprende el grupo completo y su posición excepcional.','Express past alternatives and grade epistemic force. With double infinitives, learn the complete group and its exceptional position.',[
['Separa hipótesis presente de contrafáctico pasado por el grupo verbal.','Separate present hypothesis from past counterfactual by the verb group.'],
['Con modal pasado no conviertas automáticamente el infinitivo modal en participio.','With a past modal do not automatically turn the modal infinitive into a participle.'],
['Determina si el modal expresa obligación, permiso o inferencia contextual.','Determine whether the modal expresses obligation, permission or contextual inference.']],[
T('Irrealis pasado · grupos completos aplicados','Past irrealis · complete applied groups',[['Patrón','Pattern'],['Principal','Main clause'],['Subordinada','Subordinate clause']], [['hätte + Partizip','Ich hätte den Text gelesen.','wenn ich den Text gelesen hätte'],['wäre + Partizip','Ich wäre nach Berlin gegangen.','wenn ich nach Berlin gegangen wäre'],['hätte + dos infinitivos','Ich hätte kommen können.','weil ich hätte kommen können'],['hätte + dos infinitivos','Ich hätte den Text lesen müssen.','weil ich den Text hätte lesen müssen'],[B('Condición + consecuencia','Condition + consequence'),'Wenn wir die Daten geprüft hätten, hätten wir den Fehler bemerkt.','—']],'Doble infinitivo: hätte va delante de kommen können / lesen müssen al final de la subordinada. bemerk(en) advertir; Fehler error.','Double infinitive: hätte precedes kommen können / lesen müssen in the subordinate verb cluster. bemerken notice; Fehler error.'),
T('Modalidad epistémica · fuerza y contexto','Epistemic modality · strength and context',[['Expresión','Expression'],['Lectura epistémica','Epistemic reading'],['Contraste','Contrast']], [['Das könnte stimmen.',B('Podría ser correcto.','It could be correct.'),B('Posibilidad.','Possibility.')],['Das dürfte stimmen.',B('Probablemente sea correcto.','It is probably correct.'),B('Conjetura; no permiso.','Conjecture; not permission.')],['Das muss stimmen.',B('Tiene que ser correcto (inferencia).','It must be correct (inference).'),B('También admite necesidad según contexto.','May also express necessity depending on context.')],['Das lässt sich nicht ausschließen.',B('No puede descartarse.','It cannot be ruled out.'),B('No afirma que sea probable.','Does not assert that it is probable.')],['nach bisherigem Kenntnisstand',B('según el conocimiento actual','according to current knowledge'),B('Límite explícito del alcance.','Explicit scope restriction.')]],'stimmen ser correcto; ausschließen descartar. No asignes probabilidad numérica a estos modales.','stimmen be correct; ausschließen rule out. Do not assign numerical probabilities to these modals.')], 'reading-c1-3',['reading-c1-3','reading-c1-4'],['konjunktiv2','modal-verbs','konjunktiv1','perfect']);
U(20,'Integra sintaxis y argumento: identifica proposiciones, fuente, supuesto, evidencia y alcance; luego traduce conservando esas relaciones.','Integrate syntax and argument: identify propositions, source, assumptions, evidence and scope; then translate while preserving those relations.',[
['Lee primero núcleos verbales y nominales; después despliega atributos y subordinadas.','First read verbal and nominal heads; then expand modifiers and subordinate clauses.'],
['Reconstruye premisa→conclusión y localiza atribución, cautela y objeción.','Reconstruct premise→conclusion and locate attribution, caution and objection.'],
['Traduce una vez literalmente y otra con sintaxis natural; comprueba que ambas preservan el argumento.','Translate once literally and once naturally; check that both preserve the argument.']],[
T('Argumento integrado · grupos y funciones','Integrated argument · phrases and functions',[['Segmento alemán','German segment'],['Función','Function'],['Significado','Meaning']], [['Eine Erklärung, die Verhalten vorhersagt,',B('Sujeto + relativa; vorhersagt final.','Subject + relative; vorhersagt final.'),B('Una explicación que predice conducta,','An explanation that predicts behaviour,')],['ist nicht schon deshalb vollständig,',B('Principal V2 + negación de inferencia.','Main clause V2 + negated inference.'),B('no es completa por ese solo motivo,','is not complete for that reason alone,')],['weil ihre Vorhersagen zuverlässig sind.',B('Subordinada causal; sind final.','Causal subordinate; sind final.'),B('porque sus predicciones son fiables.','because its predictions are reliable.')],['Der Autor behauptet, Bewusstsein sei erklärbar.',B('Fuente + Konjunktiv I.','Source + Konjunktiv I.'),B('El autor sostiene que la conciencia es explicable.','The author claims consciousness is explainable.')]],'La primera frase bloquea una inferencia; no niega toda posibilidad de explicación. Autor autor; vollständig completo; erklärbar explicable.','The first sentence blocks an inference; it does not deny every possibility of explanation. Autor author; vollständig complete; erklärbar explainable.'),
T('Condensación → expansión · casos aplicados','Condensation → expansion · applied cases',[['Compacto','Compact'],['Expansión','Expansion'],['Relación gramatical','Grammatical relation']], [['die Erklärung des beobachteten Verhaltens','Jemand erklärt das Verhalten, das beobachtet wurde.',B('Gen neutro des…-s; participio débil -en.','Neuter Gen des…-s; weak participle -en.')],['die Prüfung der zugrunde liegenden Annahmen','Jemand prüft die Annahmen, die zugrunde liegen.',B('Gen plural; Partizip I atributivo.','Plural Gen; attributive Partizip I.')],['die vom Autor behauptete Schlussfolgerung','die Schlussfolgerung, die der Autor behauptet hat',B('Agente von + Dat; participio como adjetivo.','Agent von + Dat; participle as adjective.')],['die Unterscheidung zwischen Vorhersage und Erklärung','Jemand unterscheidet zwischen Vorhersage und Erklärung.',B('zwischen + Dat no espacial; régimen léxico.','Non-spatial zwischen + Dat; lexical government.')]],'Reconstruir la gramática no demuestra la tesis. Mantén separados texto, paráfrasis y evaluación propia.','Reconstructing grammar does not prove the claim. Keep text, paraphrase and your own assessment separate.')], 'reading-c1-4',['reading-c1-4','reading-c1-3','reading-c1-2','reading-b2-3'],['relative','adjective-endings','genitive','connectors','konjunktiv1','passive']);
const vocab=window.DeutschData.vocabulary;
for(const [id,s] of Object.entries(S)){
  s.additionalVocabIds=[];
  s.readingGrammarIds=[...new Set(s.readingGrammarIds)];
}
fs.writeFileSync(dir+'/data/lesson-support.js', '/* Bilingual, applied instructional layer. Existing IDs remain stable. */\nwindow.DeutschData = window.DeutschData || {};\nwindow.DeutschData.lessonSupport = '+JSON.stringify(S,null,2)+';\n');
